CREATE SCHEMA IF NOT EXISTS limbo;
CREATE TABLE IF NOT EXISTS limbo.userdata(

	id INT NOT NULL AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	cpassword VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
);